### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by dominikvaradi** [BME-MIT-IET/iet-hf-2022-we-rdfs#10]
- Meg kellene tervezni egy pár(3-4) manuális teszt esetet,
- Le kell implementálni a Solutionben egy új projekt alatt felhasználva a libraryt.
- Le kell dokumentálni a teszteket.

**Comment by Teo9999** [comment]
@dominikvaradi Az általad javasolt teszteket megcsináltam. Majd kérlek nézd át őket!
Én is terveztem egy tesztet:
- Felépíteni memóriában egy egyszerű RDF gráfot országok és azok fővárosairól pl. kettő-kettő példa adattal.
- Ezután a gráfot ki lehetne írni egy RDF XML file-ba.
- Majd, hogy a beolvasás is tesztelve legyen ezt beolvasni a memóriába.
- Letesztelni, hogy tényleg 2 ország, 2 város létrejött-e query segítségével.
- Utána új várost hozzáadni a gráfhoz.
- Ezt érdemes le is tesztelni, hogy a hozzáadás után tényleg 2 ország, 3 város létezik-e query segítségével.
- Törlés se maradjon, töröljünk egy országot.
- Végül letesztelni, hogy a törlés után tényleg 1 ország, 3 város létezik-e query segítségével.

**Comment by dominikvaradi** [comment]
> @dominikvaradi Az általad javasolt teszteket megcsináltam. Majd kérlek nézd át őket! Én is terveztem egy tesztet:
> 
> * Felépíteni memóriában egy egyszerű RDF gráfot országok és azok fővárosairól pl. kettő-kettő példa adattal.
> * Ezután a gráfot ki lehetne írni egy RDF XML file-ba.
> * Majd, hogy a beolvasás is tesztelve legyen ezt beolvasni a memóriába.
> * Letesztelni, hogy tényleg 2 ország, 2 város létrejött-e query segítségével.
> * Utána új várost hozzáadni a gráfhoz.
> * Ezt érdemes le is tesztelni, hogy a hozzáadás után tényleg 2 ország, 3 város létezik-e query segítségével.
> * Törlés se maradjon, töröljünk egy országot.
> * Végül letesztelni, hogy a törlés után tényleg 1 ország, 3 város létezik-e query segítségével.

Köszi, megcsináltam a tesztet rá.

**Comment by Teo9999** [comment]
Átnéztem a tesztet, nagyon jó lett!👌
