### ISSUE TITLE
Unit tesztkézlet kibővítése, kódlefedettség alapján

### ISSUE THREAD

**Issue by TBeatrix** [BME-MIT-IET/iet-hf-2022-we-rdfs#11]

**Comment by PinterVivien** [comment]
![lefedettseg](https://user-images.githubusercontent.com/79516856/168462139-d1a75f75-16f2-442c-a625-7e44f1d057b5.png)
Ez a programunk lefedettsége most. A semantics és a query nincs lefedve, a többin nagyon szép a tesztlefedettség.

**Comment by TBeatrix** [comment]
A Szemantika package-ben nem sok logika talállható, amit tesztelni kéne, főleg konstruktorokat, interfészeket és alap ellenőrzéseket tartalaz.
A Queries-ben lévő Mirella mappa viszont sok bonyolultabb logikai függvényt tartalmaz, melyek nincsenek letesztelve, szóval szerintem ezt lenne érdemes kiegészíteni további Unit tesztekkel.

**Comment by PinterVivien** [comment]
A Szemantika package-t átvizsgáltuk manuálisan @Teo9999 -val és mi is erre jutottunk. Akkor a Queries mappát vizsgáljuk.

**Comment by TBeatrix** [comment]
Ebben a pull requestben 37 új tesztfüggvényt készítettünk el, melyekkel a Mirella mappában lévő tesztek lefedettségének növelése volt a célunk.

**Comment by TBeatrix** [comment]
Nézzük meg milyen lett az új lefedettség és hasonlítsuk össze az ezelőttivel!

**Comment by PinterVivien** [comment]
Ezek voltak az alap lefedettségek a tesztelés előtt.
![query](https://user-images.githubusercontent.com/79516856/168639087-0f18c6db-8ea1-4d11-99c1-2bca90c596dd.png)
![milerra](https://user-images.githubusercontent.com/79516856/168639092-82f3a260-b8ea-406c-aa0e-a1f5ea667194.png)

**Comment by TBeatrix** [comment]
Az új tesztekkel összesen **209 új sort** sikerült letesztelni a könyvtárból, melyekre korábban nem volt semmilyen ellenőrzés. 
Szerintem ez nagy előrelépés!

**Comment by PinterVivien** [comment]
A végleges lefedettségek. A Mirella mappa lefedettsége még 1,5%-kal nőtt, az Algebra mappa lefedettsége még 2%-ot emelkedett.
![image](https://user-images.githubusercontent.com/79516856/169138947-2955b97b-910e-4864-8e11-ac4b21ca94e4.png)
![image](https://user-images.githubusercontent.com/79516856/169139004-197f0964-6c47-4608-98d2-a55eccb1d66f.png)

**Comment by TBeatrix** [comment]
Így már tökéletes a választott függvények lehetősége!
Eddig ezek lefedettsége 0% volt, most elérték a 100%-ot!
Ezelőtt:
<img width="566" alt="FIltersFolder" src="https://user-images.githubusercontent.com/79464267/169139409-9513c230-23c1-452c-98f1-2bcad41f4ec1.PNG">

Most:
<img width="564" alt="Képkivágás2" src="https://user-images.githubusercontent.com/79464267/169139418-a17c7ef6-cee0-4191-b899-dab314cf5df3.PNG">

**Comment by TBeatrix** [comment]
**250 új sort** sikerült lefednünk **43 db** új Unit tesztetekkel!
