### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by TBeatrix** [BME-MIT-IET/iet-hf-2022-we-rdfs#3]
Az alkalmazás néhány részén lévő kód manuális átvizsgálása és véleményezése.

**Comment by PinterVivien** [comment]
A Semantics csomagra nincs teszt szerintem azt a részt kéne átnézni.

**Comment by Teo9999** [comment]
Az RDFSemanticsEnums enumokat gyűjti össze, RDFSemanticsEvents az eventeket ,RDFSemanticsException az exceptionokat amiket a Semantics tud dobni. Az RDFSemanticsUtilities a convertet végzi, RDF gráfból ontológiát. Ez rengeteg kis függvényből áll, így szerintem erre kellett volna tesztet írni.

**Comment by PinterVivien** [comment]
Igen, a gráfkonvertálásnál rengeteg lépés van kellett volna tesztelni. De alapvetően szépen fel van bontva a kód kisebb részekre és szépen le van dokumentálva mi mit csinál. Én eddig nem láttam benne hibát.

**Comment by Teo9999** [comment]
Találtam egy checklistet ami alapján végezhetnénk a kódvizsgálást:
[https://dev.to/alexomeyer/code-review-a-comprehensive-checklist-5gnm](url)

**Comment by PinterVivien** [comment]
Az 1.ponton (Verify feature requirements) biztosan átmegy, kódban megvan és dokumentálva is vannak a megvalósított funkciók.

**Comment by Teo9999** [comment]
Kód olvashatóság(Code readability) szempontjából is megfelelő a kapott kód. Jól vannak tagolva a függvények, néhol egy-egy eléggé hosszú viszont ez a téma komplexitása miatt indokolt.

**Comment by PinterVivien** [comment]
A kódolási stílus (Coding Style) megfelelel a c#-os konvencióknak: nagybetűs osztálynevek, interfészeknél I-kezdet, publikus tagokat nagybetűvel használja a privát és belső tagokhoz "_" használ és camelCaset.
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

**Comment by Teo9999** [comment]
A kódban levő osztálynevek, interfész nevek és függvény nevek érthetőek és eléggé lefedik azt, hogy pontosan milyen funkciót töltenek be. Így a kód a Clear naming ponton is átment.

**Comment by PinterVivien** [comment]
Kód duplikációt (Code duplication) manuálisan nem találtam ebben a csomagban.
(Próbáltam keresni olyan extension-t ami megkeresi a kód duplikációkat viszont nem találtam ilyet ezért csak manuálisan néztem át.)

**Comment by Teo9999** [comment]
A 6. pont a tesztek átnézése viszont erre a csomagra nincs teszt így ezeket nem tudtuk megnézni, hogy megfelelőek-e.

**Comment by PinterVivien** [comment]
A Dokumentáció (7.pont) teljesen rendben van a kód maga is végig van kommentezve a konvencióknak megfelelően 
(https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags), valamint a GitHub-on van PDF alapú dokumentáció is csomagokra bontottan.

**Comment by Teo9999** [comment]
Semantics projekt struktúrájának vizsgálata: generált osztálydiagrammból azt szűrtük le, hogy nincsenek körkörös függőségek. Vannak olyan osztályok amik csak bizonyos függvényeken belül vannak használva viszont nem mint attribútum így ezek nincsenek összekötve egyik másik osztállyal sem.

**Comment by PinterVivien** [comment]
A vizsgált diagram:
[semanticsClassDiagram.pdf](https://github.com/BME-MIT-IET/iet-hf-2022-we-rdfs/files/8644945/semanticsClassDiagram.pdf)

**Comment by TBeatrix** [comment]
Szép munka!
