### ISSUE TITLE
Sonar Cloud által jelzett hibák javítása

### ISSUE THREAD

**Issue by TBeatrix** [BME-MIT-IET/iet-hf-2022-we-rdfs#6]
SonarCloud által jelzett figyelmeztetések egy részének átvizsgálása

**Comment by TBeatrix** [comment]
A Sonar Cloud 8 _bug_ figyelmeztetést adott, ezeket megvizsgáltam, és ahol szükséges volt javítottam, a következő _pull request_-ben.
Ez sikeres volt, most már nem jelez _bug_-ot.

**Comment by maya2d26** [comment]
Véletlen zártam be a merge-elésnél.

**Comment by dominikvaradi** [comment]
Javítottam kb. 40 darab code smellt.

**Comment by maya2d26** [comment]
Én is javítottam kb 50 darab code-smellt.

**Comment by TBeatrix** [comment]
Én is kijavítottam még több _Code Smell_-t  és amelyeket nem találtam annak, azokat _False Positiv_-re állítottam. 
Valamint @maya2d26 -val átnéztük a Security Hospot jelzéseket, melyeket biztonságosnak ítéltünk, így ezt be is állítottuk Sonar Cloudon.

**Comment by TBeatrix** [comment]
Szép munka @dominikvaradi, @maya2d26 !
A legtöbb hibajelzést siskerült ellenőriznunk, és Code Smell-ből is nagyon sokat javítottunk!

Ilyen volt a SOnar Cloud jelzése első futtatásra:
![279607672_421574529307565_3195521173282104421_n](https://user-images.githubusercontent.com/79464267/169211724-22af3858-d418-4686-baf5-17ae76d0087a.png)

ÉS most ilyen:
<img width="728" alt="Képkivágás" src="https://user-images.githubusercontent.com/79464267/169211696-353210a9-9b5a-43c5-8cc9-8a2cf45af156.PNG">

Jól látszik hogy eredményesek voltunk, ezzel le is zárom az _issue_-t.
